name: ubuntu-notes-app
version: 0.4
summary: Notes application
description: Note taking application powered by Evernote
confinement: devmode  # use "strict" to enforce system access only via declared interfaces
grade: devel

apps:
    ubuntu-notes-app:
        command: desktop-launch $SNAP/usr/bin/reminders --desktop_file_hint=unity8
        plugs: [opengl, platform, unity7, unity8]

plugs:
    platform:
        interface: content
        content: ubuntu-app-platform1
        target: ubuntu-app-platform
        default-provider: ubuntu-app-platform

parts:
    ubuntu-notes-app:
        plugin: cmake
        configflags: [-DCMAKE_INSTALL_PREFIX=/usr, -DCLICK_MODE=off]
        source: .
        build-packages:
            - cmake
            - gettext
            - intltool
            - libboost-dev
            - liboxideqt-qmlplugin
            - libssl-dev
            - pkg-config
            - qt5-default
            - qtdeclarative5-dev
            - qtdeclarative5-dev-tools
            - qtpim5-dev
        stage-packages:
            - qtdeclarative5-evernote0.1
            - qml-module-qtquick-localstorage
            - signon-plugin-oauth2
        after: 
            - desktop-ubuntu-app-platform
    environment:
        source: snap/
        plugin: dump
